easy_admin:
  # On définit le nom de l'interface d'administration
  site_name: 'Gestion Bike à linge'
  # On définit l'affichage de l'utilisateur
  user:
    name_property_path: 'firstName'

  design:

    brand_color: '#1ABC9C'


  entities:
  # List the entity class name you want to manage
      - App\Entity\Order
      - App\Entity\User
